# This is a basic workflow to help you get started with Actions

name: Build and publish basespace CLI container

on:
  push:
    branches: [ "main" ]
      paths:
        -  basespace.def

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install apptainer
        run: |
          sudo apt update
          sudo apt install -y wget
          cd /tmp
          wget https://github.com/apptainer/apptainer/releases/download/v1.5.4/apptainer_1.5.4_amd64.deb
          sudo apt install -y ./apptainer_1.5.4_amd64.deb

      - name: Build SIF Image
        run: |
          apptainer build basespace.sif basespace.def

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: Push Container to GHCR
        run: |
          IMAGE_TAG=ghcr.io/${{ github.actor }}/basespace:latest
          apptainer push basespace.sif oras://$IMAGE_TAG
